application: panwdbl
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F1

handlers:
- url: /jobs/.*
  script: panwdbl.app
  login: admin

- url: /.*
  script: panwdbl.app

libraries:
- name: lxml
  version: "latest"

automatic_scaling:
  min_idle_instances: 0
  max_pending_latency: "10s"
